language: node_js
nodejs:
- stable
branches:
  only:
  - master
env:
  global:
  - REMOTE_PATH=/home/travis/uploads/travis/hello_world/travis_digitalocean
  - REMOTE_USER=travis
  - REMOTE_HOST=raivencorps.me
before_install:
- bash scripts/install.sh
after_success:
- bash scripts/deploy.sh
